ERROR - 2022-04-26 21:02:42 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-04-26 21:02:42 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\gmaps\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\gmaps\system\Database\BaseBuilder.php(1539): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#2 C:\xampp\htdocs\gmaps\app\Helpers\custom_helper.php(5): CodeIgniter\Database\BaseBuilder->countAllResults()
#3 C:\xampp\htdocs\gmaps\app\Views\home.php(22): countData('sensor')
#4 C:\xampp\htdocs\gmaps\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\gmaps\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\gmaps\system\Common.php(1089): CodeIgniter\View\View->render('home', Array, true)
#7 C:\xampp\htdocs\gmaps\app\Controllers\Home.php(9): view('home')
#8 C:\xampp\htdocs\gmaps\system\CodeIgniter.php(832): App\Controllers\Home->index()
#9 C:\xampp\htdocs\gmaps\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\gmaps\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\gmaps\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\gmaps\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-04-26 21:02:43 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\gmaps\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\gmaps\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\gmaps\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\gmaps\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\gmaps\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-04-26 21:02:48 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-04-26 21:02:48 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\gmaps\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\gmaps\system\Database\BaseBuilder.php(1539): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#2 C:\xampp\htdocs\gmaps\app\Helpers\custom_helper.php(5): CodeIgniter\Database\BaseBuilder->countAllResults()
#3 C:\xampp\htdocs\gmaps\app\Views\home.php(22): countData('sensor')
#4 C:\xampp\htdocs\gmaps\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\gmaps\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\gmaps\system\Common.php(1089): CodeIgniter\View\View->render('home', Array, true)
#7 C:\xampp\htdocs\gmaps\app\Controllers\Home.php(9): view('home')
#8 C:\xampp\htdocs\gmaps\system\CodeIgniter.php(832): App\Controllers\Home->index()
#9 C:\xampp\htdocs\gmaps\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\gmaps\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\gmaps\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\gmaps\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-04-26 21:02:49 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\gmaps\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\gmaps\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\gmaps\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\gmaps\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\gmaps\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
